project:
  type: website
  preview: 
    port: 4321
  resources:
    - /h5p
    - /atividades/desafios_online/h5p-atividades
  

website:
  title: "*obseRVe*"
  site-url: https://www.observe.ufscar.br
  navbar:
    left:
      - href: atividades/atividades.qmd
        text: Atividades 
      - href: projetos/projetos.qmd
        text: Projetos
      - href: calendario/calendario.qmd
        text: Calendário
      - href: blog/blog.qmd
        text: Blog
      - href: equipe/equipe.qmd
        text: Equipe     
      - href: acervo/acervo.qmd
        text: Acervo
      - href: localizacao/localizacao.qmd
        text: Localização  
      - href: sobre/sobre.qmd
        text: Sobre
    tools:
      - icon: instagram
        href: https://www.instagram.com/observe_ufscar 
  page-footer:
    "*obseRVe* - CCA/UFSCar<br>observe@ufscar.br"


format:
  html:
    lang: pt
    page-layout: full
    theme:
      light: [flatly, light_mode.scss]
      dark: [darkly, dark_mode.scss]
    css: styles.css
    toc: true



